/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as TentangKamiIndexRouteImport } from './routes/tentang-kami/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as TentangKamiApaItuAdopsiPohonIndexRouteImport } from './routes/tentang-kami/apa-itu-adopsi-pohon/index'
import { Route as AuthenticatedPemetaanIndexRouteImport } from './routes/_authenticated/pemetaan/index'
import { Route as AuthenticatedTentangKamiKelompokKomunitasIndexRouteImport } from './routes/_authenticated/tentang-kami/kelompok-komunitas/index'
import { Route as AuthenticatedMasterPohonIndexRouteImport } from './routes/_authenticated/master/pohon/index'
import { Route as AuthenticatedMasterPohonLokalIndexRouteImport } from './routes/_authenticated/master/pohon-lokal/index'
import { Route as AuthenticatedMasterKodePatokBatasIndexRouteImport } from './routes/_authenticated/master/kode-patok-batas/index'
import { Route as AuthenticatedDataPohonIndexRouteImport } from './routes/_authenticated/data/pohon/index'
import { Route as AuthenticatedDataPatokBatasIndexRouteImport } from './routes/_authenticated/data/patok-batas/index'
import { Route as AuthenticatedConfigUserIndexRouteImport } from './routes/_authenticated/config/user/index'
import { Route as AuthenticatedConfigRolePermissionIndexRouteImport } from './routes/_authenticated/config/role-permission/index'
import { Route as AuthenticatedTentangKamiKelompokKomunitasAddKomunitasRouteImport } from './routes/_authenticated/tentang-kami/kelompok-komunitas/add-komunitas'
import { Route as AuthenticatedMasterPohonAddMasterTreeRouteImport } from './routes/_authenticated/master/pohon/add-master-tree'
import { Route as AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRouteImport } from './routes/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/index'
import { Route as AuthenticatedMasterPohonLokalAddIndexRouteImport } from './routes/_authenticated/master/pohon-lokal/add/index'
import { Route as AuthenticatedMasterKodePatokBatasAddIndexRouteImport } from './routes/_authenticated/master/kode-patok-batas/add/index'
import { Route as AuthenticatedDataPohonAddIndexRouteImport } from './routes/_authenticated/data/pohon/add/index'
import { Route as AuthenticatedDataPohonTreeIdIndexRouteImport } from './routes/_authenticated/data/pohon/$treeId/index'
import { Route as AuthenticatedDataPatokBatasAddIndexRouteImport } from './routes/_authenticated/data/patok-batas/add/index'
import { Route as AuthenticatedDataPatokBatasBoundaryMarkerIdIndexRouteImport } from './routes/_authenticated/data/patok-batas/$boundaryMarkerId/index'
import { Route as AuthenticatedConfigUserAddIndexRouteImport } from './routes/_authenticated/config/user/add/index'
import { Route as AuthenticatedMasterPohonUpdateMasterTreeIdRouteImport } from './routes/_authenticated/master/pohon/update/$masterTreeId'
import { Route as AuthenticatedMasterPohonLokalUpdateMasterLocalTreeIdRouteImport } from './routes/_authenticated/master/pohon-lokal/update/$masterLocalTreeId'
import { Route as AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRouteImport } from './routes/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/index'
import { Route as AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRouteImport } from './routes/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/index'
import { Route as AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRouteImport } from './routes/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/index'
import { Route as AuthenticatedMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRouteImport } from './routes/_authenticated/master/kode-patok-batas/$boundaryMarkerCodeId/update/index'
import { Route as AuthenticatedDataPohonTreeIdUpdateIndexRouteImport } from './routes/_authenticated/data/pohon/$treeId/update/index'
import { Route as AuthenticatedDataPohonTreeIdSurveyHistoryIndexRouteImport } from './routes/_authenticated/data/pohon/$treeId/survey-history/index'
import { Route as AuthenticatedDataPatokBatasBoundaryMarkerIdUpdateIndexRouteImport } from './routes/_authenticated/data/patok-batas/$boundaryMarkerId/update/index'
import { Route as AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRouteImport } from './routes/_authenticated/data/patok-batas/$boundaryMarkerId/check-history/index'
import { Route as AuthenticatedConfigUserUserIdUpdateIndexRouteImport } from './routes/_authenticated/config/user/$userId/update/index'
import { Route as AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRouteImport } from './routes/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/index'
import { Route as AuthenticatedDataPohonTreeIdSurveyHistoryAddIndexRouteImport } from './routes/_authenticated/data/pohon/$treeId/survey-history/add/index'
import { Route as AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRouteImport } from './routes/_authenticated/data/patok-batas/$boundaryMarkerId/check-history/add/index'
import { Route as AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRouteImport } from './routes/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/index'
import { Route as AuthenticatedDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRouteImport } from './routes/_authenticated/data/pohon/$treeId/survey-history/$surveyHistoryId/update/index'
import { Route as AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRouteImport } from './routes/_authenticated/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update/index'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangKamiIndexRoute = TentangKamiIndexRouteImport.update({
  id: '/tentang-kami/',
  path: '/tentang-kami/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const TentangKamiApaItuAdopsiPohonIndexRoute =
  TentangKamiApaItuAdopsiPohonIndexRouteImport.update({
    id: '/tentang-kami/apa-itu-adopsi-pohon/',
    path: '/tentang-kami/apa-itu-adopsi-pohon/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPemetaanIndexRoute =
  AuthenticatedPemetaanIndexRouteImport.update({
    id: '/pemetaan/',
    path: '/pemetaan/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTentangKamiKelompokKomunitasIndexRoute =
  AuthenticatedTentangKamiKelompokKomunitasIndexRouteImport.update({
    id: '/tentang-kami/kelompok-komunitas/',
    path: '/tentang-kami/kelompok-komunitas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterPohonIndexRoute =
  AuthenticatedMasterPohonIndexRouteImport.update({
    id: '/master/pohon/',
    path: '/master/pohon/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterPohonLokalIndexRoute =
  AuthenticatedMasterPohonLokalIndexRouteImport.update({
    id: '/master/pohon-lokal/',
    path: '/master/pohon-lokal/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterKodePatokBatasIndexRoute =
  AuthenticatedMasterKodePatokBatasIndexRouteImport.update({
    id: '/master/kode-patok-batas/',
    path: '/master/kode-patok-batas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDataPohonIndexRoute =
  AuthenticatedDataPohonIndexRouteImport.update({
    id: '/data/pohon/',
    path: '/data/pohon/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDataPatokBatasIndexRoute =
  AuthenticatedDataPatokBatasIndexRouteImport.update({
    id: '/data/patok-batas/',
    path: '/data/patok-batas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigUserIndexRoute =
  AuthenticatedConfigUserIndexRouteImport.update({
    id: '/config/user/',
    path: '/config/user/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigRolePermissionIndexRoute =
  AuthenticatedConfigRolePermissionIndexRouteImport.update({
    id: '/config/role-permission/',
    path: '/config/role-permission/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTentangKamiKelompokKomunitasAddKomunitasRoute =
  AuthenticatedTentangKamiKelompokKomunitasAddKomunitasRouteImport.update({
    id: '/tentang-kami/kelompok-komunitas/add-komunitas',
    path: '/tentang-kami/kelompok-komunitas/add-komunitas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterPohonAddMasterTreeRoute =
  AuthenticatedMasterPohonAddMasterTreeRouteImport.update({
    id: '/master/pohon/add-master-tree',
    path: '/master/pohon/add-master-tree',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute =
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRouteImport.update(
    {
      id: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/',
      path: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedMasterPohonLokalAddIndexRoute =
  AuthenticatedMasterPohonLokalAddIndexRouteImport.update({
    id: '/master/pohon-lokal/add/',
    path: '/master/pohon-lokal/add/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterKodePatokBatasAddIndexRoute =
  AuthenticatedMasterKodePatokBatasAddIndexRouteImport.update({
    id: '/master/kode-patok-batas/add/',
    path: '/master/kode-patok-batas/add/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDataPohonAddIndexRoute =
  AuthenticatedDataPohonAddIndexRouteImport.update({
    id: '/data/pohon/add/',
    path: '/data/pohon/add/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDataPohonTreeIdIndexRoute =
  AuthenticatedDataPohonTreeIdIndexRouteImport.update({
    id: '/data/pohon/$treeId/',
    path: '/data/pohon/$treeId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDataPatokBatasAddIndexRoute =
  AuthenticatedDataPatokBatasAddIndexRouteImport.update({
    id: '/data/patok-batas/add/',
    path: '/data/patok-batas/add/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDataPatokBatasBoundaryMarkerIdIndexRoute =
  AuthenticatedDataPatokBatasBoundaryMarkerIdIndexRouteImport.update({
    id: '/data/patok-batas/$boundaryMarkerId/',
    path: '/data/patok-batas/$boundaryMarkerId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigUserAddIndexRoute =
  AuthenticatedConfigUserAddIndexRouteImport.update({
    id: '/config/user/add/',
    path: '/config/user/add/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterPohonUpdateMasterTreeIdRoute =
  AuthenticatedMasterPohonUpdateMasterTreeIdRouteImport.update({
    id: '/master/pohon/update/$masterTreeId',
    path: '/master/pohon/update/$masterTreeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterPohonLokalUpdateMasterLocalTreeIdRoute =
  AuthenticatedMasterPohonLokalUpdateMasterLocalTreeIdRouteImport.update({
    id: '/master/pohon-lokal/update/$masterLocalTreeId',
    path: '/master/pohon-lokal/update/$masterLocalTreeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute =
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRouteImport.update(
    {
      id: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/',
      path: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute =
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRouteImport.update(
    {
      id: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/',
      path: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute =
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRouteImport.update(
    {
      id: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/',
      path: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRoute =
  AuthenticatedMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRouteImport.update(
    {
      id: '/master/kode-patok-batas/$boundaryMarkerCodeId/update/',
      path: '/master/kode-patok-batas/$boundaryMarkerCodeId/update/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedDataPohonTreeIdUpdateIndexRoute =
  AuthenticatedDataPohonTreeIdUpdateIndexRouteImport.update({
    id: '/data/pohon/$treeId/update/',
    path: '/data/pohon/$treeId/update/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDataPohonTreeIdSurveyHistoryIndexRoute =
  AuthenticatedDataPohonTreeIdSurveyHistoryIndexRouteImport.update({
    id: '/data/pohon/$treeId/survey-history/',
    path: '/data/pohon/$treeId/survey-history/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDataPatokBatasBoundaryMarkerIdUpdateIndexRoute =
  AuthenticatedDataPatokBatasBoundaryMarkerIdUpdateIndexRouteImport.update({
    id: '/data/patok-batas/$boundaryMarkerId/update/',
    path: '/data/patok-batas/$boundaryMarkerId/update/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRoute =
  AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRouteImport.update(
    {
      id: '/data/patok-batas/$boundaryMarkerId/check-history/',
      path: '/data/patok-batas/$boundaryMarkerId/check-history/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedConfigUserUserIdUpdateIndexRoute =
  AuthenticatedConfigUserUserIdUpdateIndexRouteImport.update({
    id: '/config/user/$userId/update/',
    path: '/config/user/$userId/update/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute =
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRouteImport.update(
    {
      id: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/',
      path: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedDataPohonTreeIdSurveyHistoryAddIndexRoute =
  AuthenticatedDataPohonTreeIdSurveyHistoryAddIndexRouteImport.update({
    id: '/data/pohon/$treeId/survey-history/add/',
    path: '/data/pohon/$treeId/survey-history/add/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRoute =
  AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRouteImport.update(
    {
      id: '/data/patok-batas/$boundaryMarkerId/check-history/add/',
      path: '/data/patok-batas/$boundaryMarkerId/check-history/add/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute =
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRouteImport.update(
    {
      id: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/',
      path: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute =
  AuthenticatedDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRouteImport.update(
    {
      id: '/data/pohon/$treeId/survey-history/$surveyHistoryId/update/',
      path: '/data/pohon/$treeId/survey-history/$surveyHistoryId/update/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRoute =
  AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRouteImport.update(
    {
      id: '/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update/',
      path: '/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/tentang-kami': typeof TentangKamiIndexRoute
  '/pemetaan': typeof AuthenticatedPemetaanIndexRoute
  '/tentang-kami/apa-itu-adopsi-pohon': typeof TentangKamiApaItuAdopsiPohonIndexRoute
  '/master/pohon/add-master-tree': typeof AuthenticatedMasterPohonAddMasterTreeRoute
  '/tentang-kami/kelompok-komunitas/add-komunitas': typeof AuthenticatedTentangKamiKelompokKomunitasAddKomunitasRoute
  '/config/role-permission': typeof AuthenticatedConfigRolePermissionIndexRoute
  '/config/user': typeof AuthenticatedConfigUserIndexRoute
  '/data/patok-batas': typeof AuthenticatedDataPatokBatasIndexRoute
  '/data/pohon': typeof AuthenticatedDataPohonIndexRoute
  '/master/kode-patok-batas': typeof AuthenticatedMasterKodePatokBatasIndexRoute
  '/master/pohon-lokal': typeof AuthenticatedMasterPohonLokalIndexRoute
  '/master/pohon': typeof AuthenticatedMasterPohonIndexRoute
  '/tentang-kami/kelompok-komunitas': typeof AuthenticatedTentangKamiKelompokKomunitasIndexRoute
  '/master/pohon-lokal/update/$masterLocalTreeId': typeof AuthenticatedMasterPohonLokalUpdateMasterLocalTreeIdRoute
  '/master/pohon/update/$masterTreeId': typeof AuthenticatedMasterPohonUpdateMasterTreeIdRoute
  '/config/user/add': typeof AuthenticatedConfigUserAddIndexRoute
  '/data/patok-batas/$boundaryMarkerId': typeof AuthenticatedDataPatokBatasBoundaryMarkerIdIndexRoute
  '/data/patok-batas/add': typeof AuthenticatedDataPatokBatasAddIndexRoute
  '/data/pohon/$treeId': typeof AuthenticatedDataPohonTreeIdIndexRoute
  '/data/pohon/add': typeof AuthenticatedDataPohonAddIndexRoute
  '/master/kode-patok-batas/add': typeof AuthenticatedMasterKodePatokBatasAddIndexRoute
  '/master/pohon-lokal/add': typeof AuthenticatedMasterPohonLokalAddIndexRoute
  '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute
  '/config/user/$userId/update': typeof AuthenticatedConfigUserUserIdUpdateIndexRoute
  '/data/patok-batas/$boundaryMarkerId/check-history': typeof AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRoute
  '/data/patok-batas/$boundaryMarkerId/update': typeof AuthenticatedDataPatokBatasBoundaryMarkerIdUpdateIndexRoute
  '/data/pohon/$treeId/survey-history': typeof AuthenticatedDataPohonTreeIdSurveyHistoryIndexRoute
  '/data/pohon/$treeId/update': typeof AuthenticatedDataPohonTreeIdUpdateIndexRoute
  '/master/kode-patok-batas/$boundaryMarkerCodeId/update': typeof AuthenticatedMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRoute
  '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute
  '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute
  '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute
  '/data/patok-batas/$boundaryMarkerId/check-history/add': typeof AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRoute
  '/data/pohon/$treeId/survey-history/add': typeof AuthenticatedDataPohonTreeIdSurveyHistoryAddIndexRoute
  '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute
  '/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update': typeof AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRoute
  '/data/pohon/$treeId/survey-history/$surveyHistoryId/update': typeof AuthenticatedDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute
  '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/tentang-kami': typeof TentangKamiIndexRoute
  '/pemetaan': typeof AuthenticatedPemetaanIndexRoute
  '/tentang-kami/apa-itu-adopsi-pohon': typeof TentangKamiApaItuAdopsiPohonIndexRoute
  '/master/pohon/add-master-tree': typeof AuthenticatedMasterPohonAddMasterTreeRoute
  '/tentang-kami/kelompok-komunitas/add-komunitas': typeof AuthenticatedTentangKamiKelompokKomunitasAddKomunitasRoute
  '/config/role-permission': typeof AuthenticatedConfigRolePermissionIndexRoute
  '/config/user': typeof AuthenticatedConfigUserIndexRoute
  '/data/patok-batas': typeof AuthenticatedDataPatokBatasIndexRoute
  '/data/pohon': typeof AuthenticatedDataPohonIndexRoute
  '/master/kode-patok-batas': typeof AuthenticatedMasterKodePatokBatasIndexRoute
  '/master/pohon-lokal': typeof AuthenticatedMasterPohonLokalIndexRoute
  '/master/pohon': typeof AuthenticatedMasterPohonIndexRoute
  '/tentang-kami/kelompok-komunitas': typeof AuthenticatedTentangKamiKelompokKomunitasIndexRoute
  '/master/pohon-lokal/update/$masterLocalTreeId': typeof AuthenticatedMasterPohonLokalUpdateMasterLocalTreeIdRoute
  '/master/pohon/update/$masterTreeId': typeof AuthenticatedMasterPohonUpdateMasterTreeIdRoute
  '/config/user/add': typeof AuthenticatedConfigUserAddIndexRoute
  '/data/patok-batas/$boundaryMarkerId': typeof AuthenticatedDataPatokBatasBoundaryMarkerIdIndexRoute
  '/data/patok-batas/add': typeof AuthenticatedDataPatokBatasAddIndexRoute
  '/data/pohon/$treeId': typeof AuthenticatedDataPohonTreeIdIndexRoute
  '/data/pohon/add': typeof AuthenticatedDataPohonAddIndexRoute
  '/master/kode-patok-batas/add': typeof AuthenticatedMasterKodePatokBatasAddIndexRoute
  '/master/pohon-lokal/add': typeof AuthenticatedMasterPohonLokalAddIndexRoute
  '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute
  '/config/user/$userId/update': typeof AuthenticatedConfigUserUserIdUpdateIndexRoute
  '/data/patok-batas/$boundaryMarkerId/check-history': typeof AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRoute
  '/data/patok-batas/$boundaryMarkerId/update': typeof AuthenticatedDataPatokBatasBoundaryMarkerIdUpdateIndexRoute
  '/data/pohon/$treeId/survey-history': typeof AuthenticatedDataPohonTreeIdSurveyHistoryIndexRoute
  '/data/pohon/$treeId/update': typeof AuthenticatedDataPohonTreeIdUpdateIndexRoute
  '/master/kode-patok-batas/$boundaryMarkerCodeId/update': typeof AuthenticatedMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRoute
  '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute
  '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute
  '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute
  '/data/patok-batas/$boundaryMarkerId/check-history/add': typeof AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRoute
  '/data/pohon/$treeId/survey-history/add': typeof AuthenticatedDataPohonTreeIdSurveyHistoryAddIndexRoute
  '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute
  '/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update': typeof AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRoute
  '/data/pohon/$treeId/survey-history/$surveyHistoryId/update': typeof AuthenticatedDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute
  '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/tentang-kami/': typeof TentangKamiIndexRoute
  '/_authenticated/pemetaan/': typeof AuthenticatedPemetaanIndexRoute
  '/tentang-kami/apa-itu-adopsi-pohon/': typeof TentangKamiApaItuAdopsiPohonIndexRoute
  '/_authenticated/master/pohon/add-master-tree': typeof AuthenticatedMasterPohonAddMasterTreeRoute
  '/_authenticated/tentang-kami/kelompok-komunitas/add-komunitas': typeof AuthenticatedTentangKamiKelompokKomunitasAddKomunitasRoute
  '/_authenticated/config/role-permission/': typeof AuthenticatedConfigRolePermissionIndexRoute
  '/_authenticated/config/user/': typeof AuthenticatedConfigUserIndexRoute
  '/_authenticated/data/patok-batas/': typeof AuthenticatedDataPatokBatasIndexRoute
  '/_authenticated/data/pohon/': typeof AuthenticatedDataPohonIndexRoute
  '/_authenticated/master/kode-patok-batas/': typeof AuthenticatedMasterKodePatokBatasIndexRoute
  '/_authenticated/master/pohon-lokal/': typeof AuthenticatedMasterPohonLokalIndexRoute
  '/_authenticated/master/pohon/': typeof AuthenticatedMasterPohonIndexRoute
  '/_authenticated/tentang-kami/kelompok-komunitas/': typeof AuthenticatedTentangKamiKelompokKomunitasIndexRoute
  '/_authenticated/master/pohon-lokal/update/$masterLocalTreeId': typeof AuthenticatedMasterPohonLokalUpdateMasterLocalTreeIdRoute
  '/_authenticated/master/pohon/update/$masterTreeId': typeof AuthenticatedMasterPohonUpdateMasterTreeIdRoute
  '/_authenticated/config/user/add/': typeof AuthenticatedConfigUserAddIndexRoute
  '/_authenticated/data/patok-batas/$boundaryMarkerId/': typeof AuthenticatedDataPatokBatasBoundaryMarkerIdIndexRoute
  '/_authenticated/data/patok-batas/add/': typeof AuthenticatedDataPatokBatasAddIndexRoute
  '/_authenticated/data/pohon/$treeId/': typeof AuthenticatedDataPohonTreeIdIndexRoute
  '/_authenticated/data/pohon/add/': typeof AuthenticatedDataPohonAddIndexRoute
  '/_authenticated/master/kode-patok-batas/add/': typeof AuthenticatedMasterKodePatokBatasAddIndexRoute
  '/_authenticated/master/pohon-lokal/add/': typeof AuthenticatedMasterPohonLokalAddIndexRoute
  '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute
  '/_authenticated/config/user/$userId/update/': typeof AuthenticatedConfigUserUserIdUpdateIndexRoute
  '/_authenticated/data/patok-batas/$boundaryMarkerId/check-history/': typeof AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRoute
  '/_authenticated/data/patok-batas/$boundaryMarkerId/update/': typeof AuthenticatedDataPatokBatasBoundaryMarkerIdUpdateIndexRoute
  '/_authenticated/data/pohon/$treeId/survey-history/': typeof AuthenticatedDataPohonTreeIdSurveyHistoryIndexRoute
  '/_authenticated/data/pohon/$treeId/update/': typeof AuthenticatedDataPohonTreeIdUpdateIndexRoute
  '/_authenticated/master/kode-patok-batas/$boundaryMarkerCodeId/update/': typeof AuthenticatedMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRoute
  '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute
  '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute
  '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute
  '/_authenticated/data/patok-batas/$boundaryMarkerId/check-history/add/': typeof AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRoute
  '/_authenticated/data/pohon/$treeId/survey-history/add/': typeof AuthenticatedDataPohonTreeIdSurveyHistoryAddIndexRoute
  '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute
  '/_authenticated/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update/': typeof AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRoute
  '/_authenticated/data/pohon/$treeId/survey-history/$surveyHistoryId/update/': typeof AuthenticatedDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute
  '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/': typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/login'
    | '/not-found'
    | '/profile'
    | '/'
    | '/tentang-kami'
    | '/pemetaan'
    | '/tentang-kami/apa-itu-adopsi-pohon'
    | '/master/pohon/add-master-tree'
    | '/tentang-kami/kelompok-komunitas/add-komunitas'
    | '/config/role-permission'
    | '/config/user'
    | '/data/patok-batas'
    | '/data/pohon'
    | '/master/kode-patok-batas'
    | '/master/pohon-lokal'
    | '/master/pohon'
    | '/tentang-kami/kelompok-komunitas'
    | '/master/pohon-lokal/update/$masterLocalTreeId'
    | '/master/pohon/update/$masterTreeId'
    | '/config/user/add'
    | '/data/patok-batas/$boundaryMarkerId'
    | '/data/patok-batas/add'
    | '/data/pohon/$treeId'
    | '/data/pohon/add'
    | '/master/kode-patok-batas/add'
    | '/master/pohon-lokal/add'
    | '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId'
    | '/config/user/$userId/update'
    | '/data/patok-batas/$boundaryMarkerId/check-history'
    | '/data/patok-batas/$boundaryMarkerId/update'
    | '/data/pohon/$treeId/survey-history'
    | '/data/pohon/$treeId/update'
    | '/master/kode-patok-batas/$boundaryMarkerCodeId/update'
    | '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas'
    | '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos'
    | '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas'
    | '/data/patok-batas/$boundaryMarkerId/check-history/add'
    | '/data/pohon/$treeId/survey-history/add'
    | '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add'
    | '/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update'
    | '/data/pohon/$treeId/survey-history/$surveyHistoryId/update'
    | '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/login'
    | '/not-found'
    | '/profile'
    | '/'
    | '/tentang-kami'
    | '/pemetaan'
    | '/tentang-kami/apa-itu-adopsi-pohon'
    | '/master/pohon/add-master-tree'
    | '/tentang-kami/kelompok-komunitas/add-komunitas'
    | '/config/role-permission'
    | '/config/user'
    | '/data/patok-batas'
    | '/data/pohon'
    | '/master/kode-patok-batas'
    | '/master/pohon-lokal'
    | '/master/pohon'
    | '/tentang-kami/kelompok-komunitas'
    | '/master/pohon-lokal/update/$masterLocalTreeId'
    | '/master/pohon/update/$masterTreeId'
    | '/config/user/add'
    | '/data/patok-batas/$boundaryMarkerId'
    | '/data/patok-batas/add'
    | '/data/pohon/$treeId'
    | '/data/pohon/add'
    | '/master/kode-patok-batas/add'
    | '/master/pohon-lokal/add'
    | '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId'
    | '/config/user/$userId/update'
    | '/data/patok-batas/$boundaryMarkerId/check-history'
    | '/data/patok-batas/$boundaryMarkerId/update'
    | '/data/pohon/$treeId/survey-history'
    | '/data/pohon/$treeId/update'
    | '/master/kode-patok-batas/$boundaryMarkerCodeId/update'
    | '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas'
    | '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos'
    | '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas'
    | '/data/patok-batas/$boundaryMarkerId/check-history/add'
    | '/data/pohon/$treeId/survey-history/add'
    | '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add'
    | '/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update'
    | '/data/pohon/$treeId/survey-history/$surveyHistoryId/update'
    | '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update'
  id:
    | '__root__'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/not-found'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/tentang-kami/'
    | '/_authenticated/pemetaan/'
    | '/tentang-kami/apa-itu-adopsi-pohon/'
    | '/_authenticated/master/pohon/add-master-tree'
    | '/_authenticated/tentang-kami/kelompok-komunitas/add-komunitas'
    | '/_authenticated/config/role-permission/'
    | '/_authenticated/config/user/'
    | '/_authenticated/data/patok-batas/'
    | '/_authenticated/data/pohon/'
    | '/_authenticated/master/kode-patok-batas/'
    | '/_authenticated/master/pohon-lokal/'
    | '/_authenticated/master/pohon/'
    | '/_authenticated/tentang-kami/kelompok-komunitas/'
    | '/_authenticated/master/pohon-lokal/update/$masterLocalTreeId'
    | '/_authenticated/master/pohon/update/$masterTreeId'
    | '/_authenticated/config/user/add/'
    | '/_authenticated/data/patok-batas/$boundaryMarkerId/'
    | '/_authenticated/data/patok-batas/add/'
    | '/_authenticated/data/pohon/$treeId/'
    | '/_authenticated/data/pohon/add/'
    | '/_authenticated/master/kode-patok-batas/add/'
    | '/_authenticated/master/pohon-lokal/add/'
    | '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/'
    | '/_authenticated/config/user/$userId/update/'
    | '/_authenticated/data/patok-batas/$boundaryMarkerId/check-history/'
    | '/_authenticated/data/patok-batas/$boundaryMarkerId/update/'
    | '/_authenticated/data/pohon/$treeId/survey-history/'
    | '/_authenticated/data/pohon/$treeId/update/'
    | '/_authenticated/master/kode-patok-batas/$boundaryMarkerCodeId/update/'
    | '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/'
    | '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/'
    | '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/'
    | '/_authenticated/data/patok-batas/$boundaryMarkerId/check-history/add/'
    | '/_authenticated/data/pohon/$treeId/survey-history/add/'
    | '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/'
    | '/_authenticated/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update/'
    | '/_authenticated/data/pohon/$treeId/survey-history/$surveyHistoryId/update/'
    | '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  TentangKamiIndexRoute: typeof TentangKamiIndexRoute
  TentangKamiApaItuAdopsiPohonIndexRoute: typeof TentangKamiApaItuAdopsiPohonIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang-kami/': {
      id: '/tentang-kami/'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/tentang-kami/apa-itu-adopsi-pohon/': {
      id: '/tentang-kami/apa-itu-adopsi-pohon/'
      path: '/tentang-kami/apa-itu-adopsi-pohon'
      fullPath: '/tentang-kami/apa-itu-adopsi-pohon'
      preLoaderRoute: typeof TentangKamiApaItuAdopsiPohonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pemetaan/': {
      id: '/_authenticated/pemetaan/'
      path: '/pemetaan'
      fullPath: '/pemetaan'
      preLoaderRoute: typeof AuthenticatedPemetaanIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tentang-kami/kelompok-komunitas/': {
      id: '/_authenticated/tentang-kami/kelompok-komunitas/'
      path: '/tentang-kami/kelompok-komunitas'
      fullPath: '/tentang-kami/kelompok-komunitas'
      preLoaderRoute: typeof AuthenticatedTentangKamiKelompokKomunitasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/pohon/': {
      id: '/_authenticated/master/pohon/'
      path: '/master/pohon'
      fullPath: '/master/pohon'
      preLoaderRoute: typeof AuthenticatedMasterPohonIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/pohon-lokal/': {
      id: '/_authenticated/master/pohon-lokal/'
      path: '/master/pohon-lokal'
      fullPath: '/master/pohon-lokal'
      preLoaderRoute: typeof AuthenticatedMasterPohonLokalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/kode-patok-batas/': {
      id: '/_authenticated/master/kode-patok-batas/'
      path: '/master/kode-patok-batas'
      fullPath: '/master/kode-patok-batas'
      preLoaderRoute: typeof AuthenticatedMasterKodePatokBatasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/pohon/': {
      id: '/_authenticated/data/pohon/'
      path: '/data/pohon'
      fullPath: '/data/pohon'
      preLoaderRoute: typeof AuthenticatedDataPohonIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/patok-batas/': {
      id: '/_authenticated/data/patok-batas/'
      path: '/data/patok-batas'
      fullPath: '/data/patok-batas'
      preLoaderRoute: typeof AuthenticatedDataPatokBatasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/config/user/': {
      id: '/_authenticated/config/user/'
      path: '/config/user'
      fullPath: '/config/user'
      preLoaderRoute: typeof AuthenticatedConfigUserIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/config/role-permission/': {
      id: '/_authenticated/config/role-permission/'
      path: '/config/role-permission'
      fullPath: '/config/role-permission'
      preLoaderRoute: typeof AuthenticatedConfigRolePermissionIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tentang-kami/kelompok-komunitas/add-komunitas': {
      id: '/_authenticated/tentang-kami/kelompok-komunitas/add-komunitas'
      path: '/tentang-kami/kelompok-komunitas/add-komunitas'
      fullPath: '/tentang-kami/kelompok-komunitas/add-komunitas'
      preLoaderRoute: typeof AuthenticatedTentangKamiKelompokKomunitasAddKomunitasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/pohon/add-master-tree': {
      id: '/_authenticated/master/pohon/add-master-tree'
      path: '/master/pohon/add-master-tree'
      fullPath: '/master/pohon/add-master-tree'
      preLoaderRoute: typeof AuthenticatedMasterPohonAddMasterTreeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/': {
      id: '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/'
      path: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId'
      fullPath: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId'
      preLoaderRoute: typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/pohon-lokal/add/': {
      id: '/_authenticated/master/pohon-lokal/add/'
      path: '/master/pohon-lokal/add'
      fullPath: '/master/pohon-lokal/add'
      preLoaderRoute: typeof AuthenticatedMasterPohonLokalAddIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/kode-patok-batas/add/': {
      id: '/_authenticated/master/kode-patok-batas/add/'
      path: '/master/kode-patok-batas/add'
      fullPath: '/master/kode-patok-batas/add'
      preLoaderRoute: typeof AuthenticatedMasterKodePatokBatasAddIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/pohon/add/': {
      id: '/_authenticated/data/pohon/add/'
      path: '/data/pohon/add'
      fullPath: '/data/pohon/add'
      preLoaderRoute: typeof AuthenticatedDataPohonAddIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/pohon/$treeId/': {
      id: '/_authenticated/data/pohon/$treeId/'
      path: '/data/pohon/$treeId'
      fullPath: '/data/pohon/$treeId'
      preLoaderRoute: typeof AuthenticatedDataPohonTreeIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/patok-batas/add/': {
      id: '/_authenticated/data/patok-batas/add/'
      path: '/data/patok-batas/add'
      fullPath: '/data/patok-batas/add'
      preLoaderRoute: typeof AuthenticatedDataPatokBatasAddIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/patok-batas/$boundaryMarkerId/': {
      id: '/_authenticated/data/patok-batas/$boundaryMarkerId/'
      path: '/data/patok-batas/$boundaryMarkerId'
      fullPath: '/data/patok-batas/$boundaryMarkerId'
      preLoaderRoute: typeof AuthenticatedDataPatokBatasBoundaryMarkerIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/config/user/add/': {
      id: '/_authenticated/config/user/add/'
      path: '/config/user/add'
      fullPath: '/config/user/add'
      preLoaderRoute: typeof AuthenticatedConfigUserAddIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/pohon/update/$masterTreeId': {
      id: '/_authenticated/master/pohon/update/$masterTreeId'
      path: '/master/pohon/update/$masterTreeId'
      fullPath: '/master/pohon/update/$masterTreeId'
      preLoaderRoute: typeof AuthenticatedMasterPohonUpdateMasterTreeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/pohon-lokal/update/$masterLocalTreeId': {
      id: '/_authenticated/master/pohon-lokal/update/$masterLocalTreeId'
      path: '/master/pohon-lokal/update/$masterLocalTreeId'
      fullPath: '/master/pohon-lokal/update/$masterLocalTreeId'
      preLoaderRoute: typeof AuthenticatedMasterPohonLokalUpdateMasterLocalTreeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/': {
      id: '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas/'
      path: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas'
      fullPath: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/update-komunitas'
      preLoaderRoute: typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/': {
      id: '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos/'
      path: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos'
      fullPath: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/all-photos'
      preLoaderRoute: typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/': {
      id: '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/'
      path: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas'
      fullPath: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas'
      preLoaderRoute: typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/kode-patok-batas/$boundaryMarkerCodeId/update/': {
      id: '/_authenticated/master/kode-patok-batas/$boundaryMarkerCodeId/update/'
      path: '/master/kode-patok-batas/$boundaryMarkerCodeId/update'
      fullPath: '/master/kode-patok-batas/$boundaryMarkerCodeId/update'
      preLoaderRoute: typeof AuthenticatedMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/pohon/$treeId/update/': {
      id: '/_authenticated/data/pohon/$treeId/update/'
      path: '/data/pohon/$treeId/update'
      fullPath: '/data/pohon/$treeId/update'
      preLoaderRoute: typeof AuthenticatedDataPohonTreeIdUpdateIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/pohon/$treeId/survey-history/': {
      id: '/_authenticated/data/pohon/$treeId/survey-history/'
      path: '/data/pohon/$treeId/survey-history'
      fullPath: '/data/pohon/$treeId/survey-history'
      preLoaderRoute: typeof AuthenticatedDataPohonTreeIdSurveyHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/patok-batas/$boundaryMarkerId/update/': {
      id: '/_authenticated/data/patok-batas/$boundaryMarkerId/update/'
      path: '/data/patok-batas/$boundaryMarkerId/update'
      fullPath: '/data/patok-batas/$boundaryMarkerId/update'
      preLoaderRoute: typeof AuthenticatedDataPatokBatasBoundaryMarkerIdUpdateIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/patok-batas/$boundaryMarkerId/check-history/': {
      id: '/_authenticated/data/patok-batas/$boundaryMarkerId/check-history/'
      path: '/data/patok-batas/$boundaryMarkerId/check-history'
      fullPath: '/data/patok-batas/$boundaryMarkerId/check-history'
      preLoaderRoute: typeof AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/config/user/$userId/update/': {
      id: '/_authenticated/config/user/$userId/update/'
      path: '/config/user/$userId/update'
      fullPath: '/config/user/$userId/update'
      preLoaderRoute: typeof AuthenticatedConfigUserUserIdUpdateIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/': {
      id: '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add/'
      path: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add'
      fullPath: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/add'
      preLoaderRoute: typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/pohon/$treeId/survey-history/add/': {
      id: '/_authenticated/data/pohon/$treeId/survey-history/add/'
      path: '/data/pohon/$treeId/survey-history/add'
      fullPath: '/data/pohon/$treeId/survey-history/add'
      preLoaderRoute: typeof AuthenticatedDataPohonTreeIdSurveyHistoryAddIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/patok-batas/$boundaryMarkerId/check-history/add/': {
      id: '/_authenticated/data/patok-batas/$boundaryMarkerId/check-history/add/'
      path: '/data/patok-batas/$boundaryMarkerId/check-history/add'
      fullPath: '/data/patok-batas/$boundaryMarkerId/check-history/add'
      preLoaderRoute: typeof AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/': {
      id: '/_authenticated/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update/'
      path: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update'
      fullPath: '/tentang-kami/kelompok-komunitas/$kelompokKomunitasId/aktivitas/$groupActivityId/update'
      preLoaderRoute: typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/pohon/$treeId/survey-history/$surveyHistoryId/update/': {
      id: '/_authenticated/data/pohon/$treeId/survey-history/$surveyHistoryId/update/'
      path: '/data/pohon/$treeId/survey-history/$surveyHistoryId/update'
      fullPath: '/data/pohon/$treeId/survey-history/$surveyHistoryId/update'
      preLoaderRoute: typeof AuthenticatedDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update/': {
      id: '/_authenticated/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update/'
      path: '/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update'
      fullPath: '/data/patok-batas/$boundaryMarkerId/check-history/$checkBmHistoryId/update'
      preLoaderRoute: typeof AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPemetaanIndexRoute: typeof AuthenticatedPemetaanIndexRoute
  AuthenticatedMasterPohonAddMasterTreeRoute: typeof AuthenticatedMasterPohonAddMasterTreeRoute
  AuthenticatedTentangKamiKelompokKomunitasAddKomunitasRoute: typeof AuthenticatedTentangKamiKelompokKomunitasAddKomunitasRoute
  AuthenticatedConfigRolePermissionIndexRoute: typeof AuthenticatedConfigRolePermissionIndexRoute
  AuthenticatedConfigUserIndexRoute: typeof AuthenticatedConfigUserIndexRoute
  AuthenticatedDataPatokBatasIndexRoute: typeof AuthenticatedDataPatokBatasIndexRoute
  AuthenticatedDataPohonIndexRoute: typeof AuthenticatedDataPohonIndexRoute
  AuthenticatedMasterKodePatokBatasIndexRoute: typeof AuthenticatedMasterKodePatokBatasIndexRoute
  AuthenticatedMasterPohonLokalIndexRoute: typeof AuthenticatedMasterPohonLokalIndexRoute
  AuthenticatedMasterPohonIndexRoute: typeof AuthenticatedMasterPohonIndexRoute
  AuthenticatedTentangKamiKelompokKomunitasIndexRoute: typeof AuthenticatedTentangKamiKelompokKomunitasIndexRoute
  AuthenticatedMasterPohonLokalUpdateMasterLocalTreeIdRoute: typeof AuthenticatedMasterPohonLokalUpdateMasterLocalTreeIdRoute
  AuthenticatedMasterPohonUpdateMasterTreeIdRoute: typeof AuthenticatedMasterPohonUpdateMasterTreeIdRoute
  AuthenticatedConfigUserAddIndexRoute: typeof AuthenticatedConfigUserAddIndexRoute
  AuthenticatedDataPatokBatasBoundaryMarkerIdIndexRoute: typeof AuthenticatedDataPatokBatasBoundaryMarkerIdIndexRoute
  AuthenticatedDataPatokBatasAddIndexRoute: typeof AuthenticatedDataPatokBatasAddIndexRoute
  AuthenticatedDataPohonTreeIdIndexRoute: typeof AuthenticatedDataPohonTreeIdIndexRoute
  AuthenticatedDataPohonAddIndexRoute: typeof AuthenticatedDataPohonAddIndexRoute
  AuthenticatedMasterKodePatokBatasAddIndexRoute: typeof AuthenticatedMasterKodePatokBatasAddIndexRoute
  AuthenticatedMasterPohonLokalAddIndexRoute: typeof AuthenticatedMasterPohonLokalAddIndexRoute
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute: typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute
  AuthenticatedConfigUserUserIdUpdateIndexRoute: typeof AuthenticatedConfigUserUserIdUpdateIndexRoute
  AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRoute: typeof AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRoute
  AuthenticatedDataPatokBatasBoundaryMarkerIdUpdateIndexRoute: typeof AuthenticatedDataPatokBatasBoundaryMarkerIdUpdateIndexRoute
  AuthenticatedDataPohonTreeIdSurveyHistoryIndexRoute: typeof AuthenticatedDataPohonTreeIdSurveyHistoryIndexRoute
  AuthenticatedDataPohonTreeIdUpdateIndexRoute: typeof AuthenticatedDataPohonTreeIdUpdateIndexRoute
  AuthenticatedMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRoute: typeof AuthenticatedMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRoute
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute: typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute: typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute: typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute
  AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRoute: typeof AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRoute
  AuthenticatedDataPohonTreeIdSurveyHistoryAddIndexRoute: typeof AuthenticatedDataPohonTreeIdSurveyHistoryAddIndexRoute
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute: typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute
  AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRoute: typeof AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRoute
  AuthenticatedDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute: typeof AuthenticatedDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute: typeof AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPemetaanIndexRoute: AuthenticatedPemetaanIndexRoute,
  AuthenticatedMasterPohonAddMasterTreeRoute:
    AuthenticatedMasterPohonAddMasterTreeRoute,
  AuthenticatedTentangKamiKelompokKomunitasAddKomunitasRoute:
    AuthenticatedTentangKamiKelompokKomunitasAddKomunitasRoute,
  AuthenticatedConfigRolePermissionIndexRoute:
    AuthenticatedConfigRolePermissionIndexRoute,
  AuthenticatedConfigUserIndexRoute: AuthenticatedConfigUserIndexRoute,
  AuthenticatedDataPatokBatasIndexRoute: AuthenticatedDataPatokBatasIndexRoute,
  AuthenticatedDataPohonIndexRoute: AuthenticatedDataPohonIndexRoute,
  AuthenticatedMasterKodePatokBatasIndexRoute:
    AuthenticatedMasterKodePatokBatasIndexRoute,
  AuthenticatedMasterPohonLokalIndexRoute:
    AuthenticatedMasterPohonLokalIndexRoute,
  AuthenticatedMasterPohonIndexRoute: AuthenticatedMasterPohonIndexRoute,
  AuthenticatedTentangKamiKelompokKomunitasIndexRoute:
    AuthenticatedTentangKamiKelompokKomunitasIndexRoute,
  AuthenticatedMasterPohonLokalUpdateMasterLocalTreeIdRoute:
    AuthenticatedMasterPohonLokalUpdateMasterLocalTreeIdRoute,
  AuthenticatedMasterPohonUpdateMasterTreeIdRoute:
    AuthenticatedMasterPohonUpdateMasterTreeIdRoute,
  AuthenticatedConfigUserAddIndexRoute: AuthenticatedConfigUserAddIndexRoute,
  AuthenticatedDataPatokBatasBoundaryMarkerIdIndexRoute:
    AuthenticatedDataPatokBatasBoundaryMarkerIdIndexRoute,
  AuthenticatedDataPatokBatasAddIndexRoute:
    AuthenticatedDataPatokBatasAddIndexRoute,
  AuthenticatedDataPohonTreeIdIndexRoute:
    AuthenticatedDataPohonTreeIdIndexRoute,
  AuthenticatedDataPohonAddIndexRoute: AuthenticatedDataPohonAddIndexRoute,
  AuthenticatedMasterKodePatokBatasAddIndexRoute:
    AuthenticatedMasterKodePatokBatasAddIndexRoute,
  AuthenticatedMasterPohonLokalAddIndexRoute:
    AuthenticatedMasterPohonLokalAddIndexRoute,
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute:
    AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdIndexRoute,
  AuthenticatedConfigUserUserIdUpdateIndexRoute:
    AuthenticatedConfigUserUserIdUpdateIndexRoute,
  AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRoute:
    AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryIndexRoute,
  AuthenticatedDataPatokBatasBoundaryMarkerIdUpdateIndexRoute:
    AuthenticatedDataPatokBatasBoundaryMarkerIdUpdateIndexRoute,
  AuthenticatedDataPohonTreeIdSurveyHistoryIndexRoute:
    AuthenticatedDataPohonTreeIdSurveyHistoryIndexRoute,
  AuthenticatedDataPohonTreeIdUpdateIndexRoute:
    AuthenticatedDataPohonTreeIdUpdateIndexRoute,
  AuthenticatedMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRoute:
    AuthenticatedMasterKodePatokBatasBoundaryMarkerCodeIdUpdateIndexRoute,
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute:
    AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasIndexRoute,
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute:
    AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAllPhotosIndexRoute,
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute:
    AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdUpdateKomunitasIndexRoute,
  AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRoute:
    AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryAddIndexRoute,
  AuthenticatedDataPohonTreeIdSurveyHistoryAddIndexRoute:
    AuthenticatedDataPohonTreeIdSurveyHistoryAddIndexRoute,
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute:
    AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasAddIndexRoute,
  AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRoute:
    AuthenticatedDataPatokBatasBoundaryMarkerIdCheckHistoryCheckBmHistoryIdUpdateIndexRoute,
  AuthenticatedDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute:
    AuthenticatedDataPohonTreeIdSurveyHistorySurveyHistoryIdUpdateIndexRoute,
  AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute:
    AuthenticatedTentangKamiKelompokKomunitasKelompokKomunitasIdAktivitasGroupActivityIdUpdateIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  TentangKamiIndexRoute: TentangKamiIndexRoute,
  TentangKamiApaItuAdopsiPohonIndexRoute:
    TentangKamiApaItuAdopsiPohonIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
